# 自动生成的配置文件
# 使用以下命令构建上下文:
# CB.exe . by_config -c context_config.yaml

include_extensions: []
exclude_patterns:
- '*.log'
- '*.png'
- '*.csv'
- '*.tmp'
- '*.bak'
- '*.swp'
- '*.ipynb'
# - '*.json'
- 'context_config.yaml'
- '*summary.md'
- '**/__pycache__/*'
- '**/.git/*'
- '**/.pytest_cache/*'
- '**/.vscode/*'
- '**/node_modules/*'
- '**/dist/*'
- '**/build/*'
- '**/out/*'
- '**/.idea/*'
- .DS_Store
- Thumbs.db
include_files: []
use_gitignore: true
include_hidden: false
linemark: id

# 自定义配置指南:
# include_extensions: 包含的文件后缀 (如 ['.py', '.js'])
# exclude_patterns: 排除模式 (支持通配符)
# include_files: 特殊包含的文件 (覆盖排除规则)
# use_gitignore: 是否自动使用.gitignore规则 (true/false)
# include_hidden: 是否包括隐藏文件[以.开头的文件] (true/false)
# linemark: 是否启用linemark规则，为文本添加行号? (id/none)

# HINT:常见的排除格式：
# 1. 排除特定的后缀的文件: *.logs
# 2. 排除特定前缀的文件: **/file_prefix*
# 3. 排除特定的文件: **/file.something
# 4. 排除根目录的特定文件: file.something
# 5. 排除特定的文件夹: **/folder_name/*
# 6. 排除根目录的特定文件夹: folder_name/*
